services:

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin_password_1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d finance_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - finance-service-network


  finance-service:
    # image: ghcr.io/kurunove/
    build:
      dockerfile: Dockerfile
    container_name: finance_service
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finance_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: admin_password_1
    ports:
      - "8080:8080"
    networks:
      - finance-service-network

volumes:
  pgdata:

networks:
  finance-network:
    name: finance-service-network
    driver: bridge
